Add controllers
DiNosauur/java-shareit pull request #1
Opened 2022-09-06 12:51 UTC by DiNosauur

добавлены контроллеры для управления пользователями и вещами

2022-09-07 16:28 UTC, kukolev requested changes

2022-09-07 16:28 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (itemDto.getAvailable() == null) {
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-09-07 16:28 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        if (!service.checkUser(user)) {
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-09-08 14:18 UTC, kukolev requested changes

2022-09-08 14:18 UTC, kukolev commented on src/main/java/ru/practicum/shareit/exception/ConflictException.java
> +    public ConflictException(String s) {
Нарушение кодстайла: Переменные должны называться так, чтобы из названия можно было понять, за что отвечает переменная. Так код будет понятней при анализе.

2022-09-08 14:18 UTC, kukolev commented on src/main/java/ru/practicum/shareit/exception/ValidationException.java
> +    public ValidationException(String s) {
Нарушение кодстайла: Переменные должны называться так, чтобы из названия можно было понять, за что отвечает переменная. Так код будет понятней при анализе.

2022-09-08 14:18 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        if (repository.checkDuplicateEmail(user)) {
Этот код повторяет код из предыдущего метода. Лучше вынести валидацию в отдельный приватный метод и вызывать его из методов.

2022-09-08 14:18 UTC, kukolev commented on src/main/java/ru/practicum/shareit/exception/NotFoundException.java
> +        super(s);
Нарушение кодстайла: Переменные должны называться так, чтобы из названия можно было понять, за что отвечает переменная. Так код будет понятней при анализе.

2022-09-08 14:46 UTC, DiNosauur commented on src/main/java/ru/practicum/shareit/exception/NotFoundException.java
> +        super(s);
Исправлено

2022-09-08 14:46 UTC, DiNosauur commented on src/main/java/ru/practicum/shareit/exception/ValidationException.java
> +    public ValidationException(String s) {
Исправлено

2022-09-08 14:46 UTC, DiNosauur commented on src/main/java/ru/practicum/shareit/exception/ConflictException.java
> +    public ConflictException(String s) {
Исправлено

2022-09-08 14:46 UTC, DiNosauur commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (itemDto.getAvailable() == null) {
Исправлено

2022-09-08 14:46 UTC, DiNosauur commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        if (!service.checkUser(user)) {
Исправлено

2022-09-08 15:00 UTC, DiNosauur commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        if (repository.checkDuplicateEmail(user)) {
Исправлено

2022-09-08 21:20 UTC, kukolev approved these changes

2022-09-09 07:26 UTC, merged