Add bookings
DiNosauur/java-shareit pull request #2
Opened 2022-09-18 22:30 UTC by DiNosauur

Реализованы функции бронирования и оставления отзывов

2022-09-19 17:31 UTC, kukolev requested changes

2022-09-19 17:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingItemServiceImpl.java
> +public class BookingItemServiceImpl implements BookingService {
Логику сервисов лучше покрыть логами. Так будет проще анализировать поведение программы, если что-то пойдет не так.

2022-09-19 17:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Optional<Booking> findFirstByItemIdAndBookerIdNotAndStartBeforeOrderByStartDesc(long itemId, long userId, LocalDateTime now);
По моему такие методы очень плохо читаются в коде. Будет лучше, если названия будут короткими, а логика поиска будет реализована в `@Query`

2022-09-19 17:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>  public class ItemServiceImpl implements ItemService {
Логику сервисов лучше покрыть логами. Так будет проще анализировать поведение программы, если что-то пойдет не так.

2022-09-19 17:31 UTC, kukolev commented on src/main/resources/application.properties
> +#logging.level.org.hibernate.SQL=debug
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-09-19 17:31 UTC, kukolev commented on src/main/resources/application.properties
> +#jdbc.driverClassName=org.postgresql.Driver
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-09-19 22:25 UTC, DiNosauur commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Optional<Booking> findFirstByItemIdAndBookerIdNotAndStartBeforeOrderByStartDesc(long itemId, long userId, LocalDateTime now);
реализовал

2022-09-19 22:25 UTC, DiNosauur commented on src/main/java/ru/practicum/shareit/booking/BookingItemServiceImpl.java
> +public class BookingItemServiceImpl implements BookingService {
Добавил

2022-09-19 22:26 UTC, DiNosauur commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>  public class ItemServiceImpl implements ItemService {
Добавил

2022-09-19 22:26 UTC, DiNosauur commented on src/main/resources/application.properties
> +#logging.level.org.hibernate.SQL=debug
удалил

2022-09-19 22:26 UTC, DiNosauur commented on src/main/resources/application.properties
> +#jdbc.driverClassName=org.postgresql.Driver
удалил

2022-09-20 11:52 UTC, kukolev requested changes

2022-09-20 11:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingItemServiceImpl.java
> +        log.info(String.format("Заявка на бронирование (%s) от пользователя (id=%s)",
При логировании лучше использовать возможности библиотеки и пользоваться плейсхолдерами `{}` вместо конкатенации строк. Лучше так: `log.warn("Some warning text for {}", val)` вместо `log.warn("Some warning text for " + val)` или `log.warn(String.format("Some warning text for %s", val))` . Так код смотрится проще и тратится меньше ресурсов.

Аналогично нужно поправить в остальных местах кода, где есть логирование.

2022-09-20 11:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        log.info(String.format("Поиск всех вещей пользователя (id=%s)", userId));
При логировании лучше использовать возможности библиотеки и пользоваться плейсхолдерами `{}` вместо конкатенации строк. Лучше так: `log.warn("Some warning text for {}", val)` вместо `log.warn("Some warning text for " + val)` или `log.warn(String.format("Some warning text for %s", val))` . Так код смотрится проще и тратится меньше ресурсов.

Аналогично нужно поправить в остальных местах кода, где есть логирование.

2022-09-20 13:30 UTC, DiNosauur commented on src/main/java/ru/practicum/shareit/booking/BookingItemServiceImpl.java
> +        log.info(String.format("Заявка на бронирование (%s) от пользователя (id=%s)",
Поправил

2022-09-20 13:30 UTC, DiNosauur commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        log.info(String.format("Поиск всех вещей пользователя (id=%s)", userId));
Поправил

2022-09-20 17:16 UTC, kukolev approved these changes

2022-09-21 07:16 UTC, merged