feat: добавлен запрос вещи
DiNosauur/java-shareit pull request #3
Opened 2022-10-01 14:51 UTC by DiNosauur

Добавлены возможности создавать запрос вещи и добавлять вещи в ответ на запросы других пользователей

2022-10-09 09:44 UTC, kukolev requested changes

2022-10-09 09:44 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Page<Booking> findAllByBookerIdAndStartBeforeAndEndAfter(long bookerId, LocalDateTime start, LocalDateTime end, Pageable pageable);
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-09 09:44 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    void findLastBooking() {
Этот тест нужно разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Хороший юнит тест состоит из трех блоков кода:

1. Подготовка данных для теста
2. Вызов тестируемого метода
3. Проверка результатов

Важно, чтобы п.2 выполнялся однократно - так будет проще понять что пошло не так, если один или несколько тестов упадут.

Подробнее о хороших практиках юнит-тестирования можно прочитать тут:  https://www.baeldung.com/java-unit-testing-best-practices

Также нужно поправить остальные подобные тесты, в которых тестируемый код вызывается больше одного раза.

2022-10-09 09:44 UTC, kukolev commented on src/test/java/ru/practicum/shareit/request/ItemRequestControllerTest.java
> +    ItemRequestService service;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-09 12:30 UTC, DiNosauur commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Page<Booking> findAllByBookerIdAndStartBeforeAndEndAfter(long bookerId, LocalDateTime start, LocalDateTime end, Pageable pageable);
Исправлено

2022-10-09 12:32 UTC, DiNosauur commented on src/test/java/ru/practicum/shareit/request/ItemRequestControllerTest.java
> +    ItemRequestService service;
Исправлено

2022-10-09 14:29 UTC, DiNosauur commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    void findLastBooking() {
Исправлено

2022-10-10 12:27 UTC, kukolev requested changes

2022-10-10 12:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void updateBooking() throws Exception {
Не исправлено замечание:  https://github.com/DiNosauur/java-shareit/pull/3#discussion_r990764130
Нужно исправить.

2022-10-10 12:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void findBookingById() throws Exception {
Не исправлено замечание:  https://github.com/DiNosauur/java-shareit/pull/3#discussion_r990764130
Нужно исправить.

2022-10-10 12:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    void updateItem() throws Exception {
Не исправлено замечание:  https://github.com/DiNosauur/java-shareit/pull/3#discussion_r990764130
Нужно исправить.

2022-10-10 12:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    void findItemById() throws Exception {
Не исправлено замечание:  https://github.com/DiNosauur/java-shareit/pull/3#discussion_r990764130
Нужно исправить.

2022-10-10 12:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    void deleteItemById() throws Exception {
Не исправлено замечание:  https://github.com/DiNosauur/java-shareit/pull/3#discussion_r990764130
Нужно исправить.

2022-10-10 12:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    void addItemComment() throws Exception {
Не исправлено замечание:  https://github.com/DiNosauur/java-shareit/pull/3#discussion_r990764130
Нужно исправить.

2022-10-10 12:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    void saveItem() {
Не исправлено замечание:  https://github.com/DiNosauur/java-shareit/pull/3#discussion_r990764130
Нужно исправить.

2022-10-10 12:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    void updateItem() {
Не исправлено замечание:  https://github.com/DiNosauur/java-shareit/pull/3#discussion_r990764130
Нужно исправить.

2022-10-10 12:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    void addItemComment() {
Не исправлено замечание:  https://github.com/DiNosauur/java-shareit/pull/3#discussion_r990764130
Нужно исправить.

2022-10-10 12:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/request/ItemRequestControllerTest.java
> +    void findItemById() throws Exception {
Не исправлено замечание:  https://github.com/DiNosauur/java-shareit/pull/3#discussion_r990764130
Нужно исправить.

2022-10-10 12:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/request/ItemRequestServiceImplTest.java
> +    void findAllItemRequests() {
Не исправлено замечание:  https://github.com/DiNosauur/java-shareit/pull/3#discussion_r990764130
Нужно исправить.

2022-10-10 12:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    void updateUser() throws Exception {
Не исправлено замечание:  https://github.com/DiNosauur/java-shareit/pull/3#discussion_r990764130
Нужно исправить.

2022-10-10 12:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    void findUserById() throws Exception {
Не исправлено замечание:  https://github.com/DiNosauur/java-shareit/pull/3#discussion_r990764130
Нужно исправить.

2022-10-10 12:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    void deleteUserById() throws Exception {
Не исправлено замечание:  https://github.com/DiNosauur/java-shareit/pull/3#discussion_r990764130
Нужно исправить.

2022-10-10 12:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/user/UserServiceImplTest.java
> +    void updateUser() {
Не исправлено замечание:  https://github.com/DiNosauur/java-shareit/pull/3#discussion_r990764130
Нужно исправить.

2022-10-11 17:15 UTC, DiNosauur commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void updateBooking() throws Exception {
Исправлено

2022-10-11 17:15 UTC, DiNosauur commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void findBookingById() throws Exception {
Исправлено

2022-10-11 17:16 UTC, DiNosauur commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    void updateItem() throws Exception {
Исправлено

2022-10-11 17:16 UTC, DiNosauur commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    void findItemById() throws Exception {
Исправлено

2022-10-11 17:16 UTC, DiNosauur commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    void deleteItemById() throws Exception {
Исправлено

2022-10-11 17:16 UTC, DiNosauur commented on src/test/java/ru/practicum/shareit/request/ItemRequestServiceImplTest.java
> +    void findAllItemRequests() {
Исправлено

2022-10-11 17:16 UTC, DiNosauur commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    void addItemComment() throws Exception {
Исправлено

2022-10-11 17:16 UTC, DiNosauur commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    void saveItem() {
Исправлено

2022-10-11 17:16 UTC, DiNosauur commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    void updateItem() {
Исправлено

2022-10-11 17:16 UTC, DiNosauur commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    void addItemComment() {
Исправлено

2022-10-11 17:16 UTC, DiNosauur commented on src/test/java/ru/practicum/shareit/request/ItemRequestControllerTest.java
> +    void findItemById() throws Exception {
Исправлено

2022-10-11 17:17 UTC, DiNosauur commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    void updateUser() throws Exception {
Исправлено

2022-10-11 17:17 UTC, DiNosauur commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    void findUserById() throws Exception {
Исправлено

2022-10-11 17:17 UTC, DiNosauur commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    void deleteUserById() throws Exception {
Исправлено

2022-10-11 17:17 UTC, DiNosauur commented on src/test/java/ru/practicum/shareit/user/UserServiceImplTest.java
> +    void updateUser() {
Исправлено

2022-10-12 12:51 UTC, kukolev approved these changes

2022-10-31 08:51 UTC, merged